FROM ruby:2.2.10

#
# Set some env variables
#
ENV APP_HOME /cc-log-manager
ENV BUNDLE_PATH /bundle

#
# Create app dir and set it as workdir
#
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

#
# Install npm
#
RUN apt-get update && apt-get install -y npm

#
# update bundler since version in rails:4.2 is older
#
RUN gem install bundler -v 1.17.3

#
# Spring has a bug where it doesn't respect BUNDLER environment variables
# https://github.com/rails/spring/issues/339
#
ADD docker/dev/spring.rb /root/.spring.rb

#
# Expose UI port
#
EXPOSE 3000

#
# Start rails
#
CMD rails s -b 0.0.0.0
